-- Fashion Date — initial PostgreSQL schema for Supabase.
-- Safe to execute more than once in the Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lucky_number TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  store TEXT NOT NULL,
  phone TEXT NOT NULL UNIQUE,
  instagram TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_participants_status
  ON public.participants (status);

CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO public.settings (key, value)
VALUES ('registrations_open', 'true')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.draws (
  id UUID PRIMARY KEY,
  participant_id BIGINT NOT NULL
    REFERENCES public.participants(id) ON DELETE CASCADE,
  lucky_number TEXT NOT NULL,
  drawn_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_draws_participant_id
  ON public.draws (participant_id);

CREATE TABLE IF NOT EXISTS public.request_rate_limits (
  key TEXT PRIMARY KEY,
  window_started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  request_count INTEGER NOT NULL DEFAULT 1
);

-- The website accesses these tables only through server-side Route Handlers.
-- Enabling RLS with no public policies prevents direct anonymous API access.
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.draws ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.request_rate_limits ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.participants FROM anon, authenticated;
REVOKE ALL ON TABLE public.settings FROM anon, authenticated;
REVOKE ALL ON TABLE public.draws FROM anon, authenticated;
REVOKE ALL ON TABLE public.request_rate_limits FROM anon, authenticated;
